### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by quantenzitrone** [leonmavr/retrocube#7]
i haven't investigated further, but when trying to run it with
```
nix run github:leonmavr/retrocube
```
i get a SIGSEGV

so your code seems to be broken

**Comment by leonmavr** [comment]
Hey @Quantenzitrone, thanks for reporting it.

I think I figured out what was the issue and I pushed a commit in the demo to fix it.

Can you check if it works now? You should see the cube again if it does.

**Comment by quantenzitrone** [comment]
nope, still segvaults :confused:

**Comment by quantenzitrone** [comment]
weirdly, when i clone the repo and compile it with make, it works
wait, when i compile it with nix build or nix run from the cloned repo it works too
only `nix run github:leonmavr/retrocube` segvaults
what?

**Comment by leonmavr** [comment]
Very weird error. I read that nix captures its dependencies in a hash. Since I removed the ncurses from the project I manually updated the default.nix to remove that dependency so maybe that messed up the hash there. Anyway, I added the dependency back to the file. I'm just shooting in the dark and I have no idea if it will fix the issue but there's no harm trying. I don't use nix so unfortunately I cannot try running it myself.

**Comment by quantenzitrone** [comment]
its depending on the working directory
https://github.com/leonmavr/retrocube/blob/2fb69a632ce275466a1e52aeb4e984749b9933a0/main.c#L101-L108
if the current working directory doesn't contain `mesh_files/cube.scl`, it segvaults because it can't find the file.
im not sure what the best practices here are, but i think you have to install the meshes to $PREFIX/share and link the files from there in your code
